# Generated by Django 5.2.9 on 2026-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('topic_id', models.CharField(db_index=True, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user_uid', 'course_id', 'topic_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user_uid', 'course_id')},
            },
        ),
    ]
