# Generated by Django 5.2.9 on 2026-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quizquestion_alter_topicprogress_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_uid', 'date')},
            },
        ),
    ]
